---
jobs:

  - name: plan-inspection-vpc
    plan:
      - in_parallel:
          - get: pipeline-tasks
            params: {depth: 1}
          - get: terraform-provision-repo
            # trigger: true
            params: {depth: 1}
      - task: terraform-plan-inspection-vpc
        tags: [iaas]
        file: pipeline-tasks/terraform-apply.yml
        input_mapping: {terraform-templates: terraform-provision-repo}
        params: &firewall-inspection-vpc-params
          TERRAFORM_ACTION: plan
          STACK_NAME: firewall-inspection-vpc
          TEMPLATE_SUBDIR: terraform/stacks/firewall-inspection-vpc
          S3_TFSTATE_BUCKET: ((aws_s3_tfstate_bucket))
          AWS_DEFAULT_REGION: ((aws_default_region))
          TF_VAR_name_prefix: "nfw-inspection"
          TF_VAR_tags: |
            {
              owner  = "Steve"
              status = "development"
            }
          TF_VAR_inspection_vpc_cidr: "10.100.0.0/16"
          TF_VAR_availability_zones: ["us-gov-west-1a", "us-gov-west-1b"]
          TF_VAR_firewall_subnet_cidrs: ["10.100.0.0/28", "10.100.0.16/28"]
          TF_VAR_tgw_subnet_cidrs: ["10.100.1.0/28", "10.100.1.16/28"]
          TF_VAR_public_subnet_cidrs: ["10.100.2.0/28", "10.100.2.16/28"]
          TF_VAR_firewall_managed_rule_groups: |
            [{
              resource_name            = "AttackInfrastructureStrictOrder"
              priority                 = 1
              override_action_to_count = true
            }]
          TF_VAR_delete_protection: false
          TF_VAR_logging_enabled: true
          TF_VAR_log_retention_days: 1
  - name: apply-inspection-vpc
    plan:
      - in_parallel:
          - get: pipeline-tasks
            params: {depth: 1}
          - get: terraform-provision-repo
            # trigger: true
            params: {depth: 1}
            passed: [plan-inspection-vpc]
      - task: terraform-apply-inspection-vpc
        tags: [iaas]
        file: pipeline-tasks/terraform-apply.yml
        input_mapping: {terraform-templates: terraform-provision-repo}
        params:
          <<: *firewall-inspection-vpc-params
          TERRAFORM_ACTION: apply
resources:
  - name: pipeline-tasks
    type: git
    source:
      uri: https://github.com/cloud-gov/pipeline-tasks
      branch: main
      commit_verification_keys: ((cloud-gov-pgp-keys))
  - name: terraform-provision-repo
    type: git
    source:
      uri: https://github.com/cloud-gov/terraform-provision
      branch: firewall-inspection-vpc
      commit_verification_keys: ((cloud-gov-pgp-keys))

resource_types:
  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: s3-iam
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: s3-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: git
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: git-resource
      aws_region: us-gov-west-1
      tag: latest
