jobs:
- name: pull-status-check
  plan:
  - get: pull-request
    version: every
    trigger: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: validate-terraform
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 18fgsa/concourse-task
      inputs:
      - name: pull-request
      run:
        path: pull-request/validate.sh
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure

- name: plan-bootstrap-external-staging
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      trigger: true
  - task: plan-update-external-staging
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params: &external-staging-params
      TERRAFORM_ACTION: plan
      STACK_NAME: external-staging
      TEMPLATE_SUBDIR: terraform/stacks/external
      S3_TFSTATE_BUCKET: {{aws_external_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_external_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_external_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_external_region}}
      TF_VAR_aws_partition: {{aws_external_partition}}
      TF_VAR_aws_default_region: {{aws_external_region}}
      TF_VAR_account_id: {{aws_external_account_id}}
      TF_VAR_cdn_broker_username: {{cdn_broker_username_staging}}
      TF_VAR_cdn_broker_bucket: {{cdn_broker_bucket_staging}}
      TF_VAR_cdn_broker_cloudfront_prefix: {{cdn_broker_cloudfront_prefix_staging}}
      TF_VAR_cdn_broker_hosted_zone: {{cdn_broker_hosted_zone_staging}}

- name: bootstrap-external-staging
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      passed: [plan-bootstrap-external-staging]
  - task: create-update-external-staging
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      <<: *external-staging-params
      TERRAFORM_ACTION: apply

- name: plan-bootstrap-external-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      trigger: true
  - task: plan-update-external-production
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params: &external-production-params
      TERRAFORM_ACTION: plan
      STACK_NAME: external-production
      TEMPLATE_SUBDIR: terraform/stacks/external
      S3_TFSTATE_BUCKET: {{aws_external_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_external_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_external_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_external_region}}
      TF_VAR_aws_partition: {{aws_external_partition}}
      TF_VAR_aws_default_region: {{aws_external_region}}
      TF_VAR_account_id: {{aws_external_account_id}}
      TF_VAR_cdn_broker_username: {{cdn_broker_username_production}}
      TF_VAR_cdn_broker_bucket: {{cdn_broker_bucket_production}}
      TF_VAR_cdn_broker_cloudfront_prefix: {{cdn_broker_cloudfront_prefix_production}}
      TF_VAR_cdn_broker_hosted_zone: {{cdn_broker_hosted_zone_production}}

- name: bootstrap-external-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      passed: [plan-bootstrap-external-production]
  - task: create-update-external-production
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      <<: *external-production-params
      TERRAFORM_ACTION: apply

- name: plan-bootstrap-tooling
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      trigger: true
  - task: plan-update-tooling
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params: &tooling-params
      TERRAFORM_ACTION: plan
      STACK_NAME: tooling
      TEMPLATE_SUBDIR: terraform/stacks/tooling
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}
      TF_VAR_az1: {{aws_az1}}
      TF_VAR_az2: {{aws_az2}}
      TF_VAR_aws_partition: {{aws_partition}}
      TF_VAR_aws_default_region: {{aws_default_region}}
      TF_VAR_account_id: {{aws_account_id}}
      TF_VAR_rds_password: {{tooling_rds_password}}
      TF_VAR_concourse_prod_rds_password: {{concourse_prod_rds_password}}
      TF_VAR_concourse_prod_cidr: {{concourse_prod_cidr}}
      TF_VAR_concourse_staging_rds_password: {{concourse_staging_rds_password}}
      TF_VAR_concourse_staging_cidr: {{concourse_staging_cidr}}
      TF_VAR_monitoring_staging_cidr: {{monitoring_staging_cidr}}
      TF_VAR_monitoring_production_cidr: {{monitoring_production_cidr}}
      TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
      TF_VAR_vpc_cidr: {{tooling_vpc_cidr}}
      TF_VAR_public_cidr_1: {{tooling_public_cidr_1}}
      TF_VAR_public_cidr_2: {{tooling_public_cidr_2}}
      TF_VAR_private_cidr_1: {{tooling_private_cidr_1}}
      TF_VAR_private_cidr_2: {{tooling_private_cidr_2}}
      TF_VAR_rds_private_cidr_1: {{tooling_rds_private_cidr_1}}
      TF_VAR_rds_private_cidr_2: {{tooling_rds_private_cidr_2}}
      TF_VAR_restricted_ingress_web_cidrs: {{tooling_restricted_ingress_web_cidrs}}

- name: bootstrap-tooling
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      passed: [plan-bootstrap-tooling]
  - task: create-update-tooling
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      <<: *tooling-params
      TERRAFORM_ACTION: apply
  - task: init-bosh-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        BOSH_DB_PASSWORD: {{tooling_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
        STACK_NAME: tooling
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-bosh-db.sh

- name: plan-bootstrap-staging
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      trigger: true
  - task: plan-update-staging
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params: &staging-params
      TERRAFORM_ACTION: plan
      STACK_NAME: staging
      TEMPLATE_SUBDIR: terraform/stacks/staging
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}
      TF_VAR_az1: {{aws_az1}}
      TF_VAR_az2: {{aws_az2}}
      TF_VAR_aws_partition: {{aws_partition}}
      TF_VAR_account_id: {{aws_account_id}}
      TF_VAR_rds_password: {{staging_rds_password}}
      TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
      TF_VAR_vpc_cidr: {{staging_vpc_cidr}}
      TF_VAR_public_cidr_1: {{staging_public_cidr_1}}
      TF_VAR_public_cidr_2: {{staging_public_cidr_2}}
      TF_VAR_private_cidr_1: {{staging_private_cidr_1}}
      TF_VAR_private_cidr_2: {{staging_private_cidr_2}}
      TF_VAR_services_cidr_1: {{staging_services_cidr_1}}
      TF_VAR_services_cidr_2: {{staging_services_cidr_2}}
      TF_VAR_kubernetes_cluster_id: {{staging_kubernetes_cluster_id}}
      TF_VAR_rds_private_cidr_1: {{staging_rds_private_cidr_1}}
      TF_VAR_rds_private_cidr_2: {{staging_rds_private_cidr_2}}
      TF_VAR_cf_rds_password: {{staging_cf_rds_password}}
      TF_VAR_restricted_ingress_web_cidrs: {{staging_restricted_ingress_web_cidrs}}
      TF_VAR_diego_cidr_1: {{staging_diego_cidr_1}}
      TF_VAR_diego_cidr_2: {{staging_diego_cidr_2}}
      TF_VAR_concourse_rds_password: {{staging_vpc_concourse_rds_password}}
      TF_VAR_concourse_cidr: {{staging_vpc_concourse_cidr}}

- name: bootstrap-staging
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      passed: [plan-bootstrap-staging]
  - task: create-update-staging
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      <<: *staging-params
      TERRAFORM_ACTION: apply
  - task: init-bosh-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        BOSH_DB_PASSWORD: {{staging_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
        STACK_NAME: staging
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-bosh-db.sh
  - task: init-cf-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        CF_DB_PASSWORD: {{staging_cf_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
        STACK_NAME: staging
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-cf-db.sh

- name: plan-bootstrap-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      trigger: true
  - task: plan-update-production
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params: &production-params
      TERRAFORM_ACTION: plan
      STACK_NAME: production
      TEMPLATE_SUBDIR: terraform/stacks/production
      S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_DEFAULT_REGION: {{aws_default_region}}
      TF_VAR_az1: {{aws_az1}}
      TF_VAR_az2: {{aws_az2}}
      TF_VAR_aws_partition: {{aws_partition}}
      TF_VAR_account_id: {{aws_account_id}}
      TF_VAR_rds_password: {{production_rds_password}}
      TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
      TF_VAR_vpc_cidr: {{production_vpc_cidr}}
      TF_VAR_public_cidr_1: {{production_public_cidr_1}}
      TF_VAR_public_cidr_2: {{production_public_cidr_2}}
      TF_VAR_private_cidr_1: {{production_private_cidr_1}}
      TF_VAR_private_cidr_2: {{production_private_cidr_2}}
      TF_VAR_services_cidr_1: {{production_services_cidr_1}}
      TF_VAR_services_cidr_2: {{production_services_cidr_2}}
      TF_VAR_kubernetes_cluster_id: {{production_kubernetes_cluster_id}}
      TF_VAR_rds_private_cidr_1: {{production_rds_private_cidr_1}}
      TF_VAR_rds_private_cidr_2: {{production_rds_private_cidr_2}}
      TF_VAR_cf_rds_password: {{production_cf_rds_password}}
      TF_VAR_restricted_ingress_web_cidrs: {{production_restricted_ingress_web_cidrs}}
      TF_VAR_diego_cidr_1: {{production_diego_cidr_1}}
      TF_VAR_diego_cidr_2: {{production_diego_cidr_2}}
      TF_VAR_concourse_rds_password: {{production_vpc_concourse_rds_password}}
      TF_VAR_concourse_cidr: {{production_vpc_concourse_cidr}}

- name: bootstrap-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: cg-provision-repo
      passed: [plan-bootstrap-production]
  - task: create-update-production
    file: pipeline-tasks/terraform-apply.yml
    input_mapping: { terraform-templates: cg-provision-repo }
    params:
      <<: *production-params
      TERRAFORM_ACTION: apply
  - task: init-bosh-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        BOSH_DB_PASSWORD: {{production_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
        STACK_NAME: production
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-bosh-db.sh
  - task: init-cf-db
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/psql
      inputs:
        - name: cg-provision-repo
        - name: terraform-state
      params:
        CF_DB_PASSWORD: {{production_cf_rds_password}}
        STATE_FILE_PATH: terraform-state/terraform.tfstate
        STACK_NAME: production
      run:
        path: sh
        args:
        - -e
        - -c
        - cg-provision-repo/ci/scripts/update-cf-db.sh

# - name: teardown-tooling
#   plan:
#   - aggregate:
#     - get: pipeline-tasks
#     - get: cg-provision-repo
#       passed: [teardown-staging, teardown-production]
#   - task: destroy
#     file: pipeline-tasks/terraform-destroy.yml
#     input_mapping: { terraform-templates: cg-provision-repo }
#     params:
#       STACK_NAME: tooling
#       TEMPLATE_SUBDIR: terraform/stacks/tooling
#       S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
#       AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
#       AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
#       AWS_DEFAULT_REGION: {{aws_default_region}}
#       TF_VAR_az1: {{aws_az1}}
#       TF_VAR_az2: {{aws_az2}}
#       TF_VAR_account_id: {{aws_account_id}}
#       TF_VAR_rds_password: {{tooling_rds_password}}
#       TF_VAR_concourse_prod_rds_password: {{concourse_prod_rds_password}}
#       TF_VAR_concourse_prod_cidr: {{concourse_prod_cidr}}
#       TF_VAR_concourse_staging_rds_password: {{concourse_staging_rds_password}}
#       TF_VAR_concourse_staging_cidr: {{concourse_staging_cidr}}
#       TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
#       TF_VAR_vpc_cidr: {{tooling_vpc_cidr}}
#       TF_VAR_public_cidr_1: {{tooling_public_cidr_1}}
#       TF_VAR_public_cidr_2: {{tooling_public_cidr_2}}
#       TF_VAR_private_cidr_1: {{tooling_private_cidr_1}}
#       TF_VAR_private_cidr_2: {{tooling_private_cidr_2}}
#       TF_VAR_rds_private_cidr_1: {{tooling_rds_private_cidr_1}}
#       TF_VAR_rds_private_cidr_2: {{tooling_rds_private_cidr_2}}

# - name: teardown-staging
#   plan:
#   - aggregate:
#     - get: pipeline-tasks
#     - get: cg-provision-repo
#       passed: [bootstrap-staging]
#   - task: destroy
#     file: pipeline-tasks/terraform-destroy.yml
#     input_mapping: { terraform-templates: cg-provision-repo }
#     params:
#       STACK_NAME: staging
#       TEMPLATE_SUBDIR: terraform/stacks/staging
#       S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
#       AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
#       AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
#       AWS_DEFAULT_REGION: {{aws_default_region}}
#       TF_VAR_az1: {{aws_az1}}
#       TF_VAR_az2: {{aws_az2}}
#       TF_VAR_account_id: {{aws_account_id}}
#       TF_VAR_rds_password: {{staging_rds_password}}
#       TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
#       TF_VAR_vpc_cidr: {{staging_vpc_cidr}}
#       TF_VAR_public_cidr_1: {{staging_public_cidr_1}}
#       TF_VAR_public_cidr_2: {{staging_public_cidr_2}}
#       TF_VAR_private_cidr_1: {{staging_private_cidr_1}}
#       TF_VAR_private_cidr_2: {{staging_private_cidr_2}}
#       TF_VAR_rds_private_cidr_1: {{staging_rds_private_cidr_1}}
#       TF_VAR_rds_private_cidr_2: {{staging_rds_private_cidr_2}}

# - name: teardown-production
#   plan:
#   - aggregate:
#     - get: pipeline-tasks
#     - get: cg-provision-repo
#       passed: [bootstrap-production]
#   - task: destroy
#     file: pipeline-tasks/terraform-destroy.yml
#     input_mapping: { terraform-templates: cg-provision-repo }
#     params:
#       STACK_NAME: production
#       TEMPLATE_SUBDIR: terraform/stacks/production
#       S3_TFSTATE_BUCKET: {{aws_s3_tfstate_bucket}}
#       AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
#       AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
#       AWS_DEFAULT_REGION: {{aws_default_region}}
#       TF_VAR_az1: {{aws_az1}}
#       TF_VAR_az2: {{aws_az2}}
#       TF_VAR_account_id: {{aws_account_id}}
#       TF_VAR_rds_password: {{production_rds_password}}
#       TF_VAR_remote_state_bucket: {{aws_s3_tfstate_bucket}}
#       TF_VAR_vpc_cidr: {{production_vpc_cidr}}
#       TF_VAR_public_cidr_1: {{production_public_cidr_1}}
#       TF_VAR_public_cidr_2: {{production_public_cidr_2}}
#       TF_VAR_private_cidr_1: {{production_private_cidr_1}}
#       TF_VAR_private_cidr_2: {{production_private_cidr_2}}
#       TF_VAR_rds_private_cidr_1: {{production_rds_private_cidr_1}}
#       TF_VAR_rds_private_cidr_2: {{production_rds_private_cidr_2}}

resources:
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline_tasks_git_url}}
    branch: {{pipeline_tasks_git_branch}}

- name: cg-provision-repo
  type: git
  source:
    uri: {{cg_provision_git_url}}
    branch: {{cg_provision_git_branch}}

- name: pull-request
  type: pull-request
  source:
    repo: {{cg_provision_git_repo}}
    access_token: {{status_access_token}}
    every: true

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
